name: Rollback

on:
  workflow_dispatch:
    inputs:
      backup_s3_key:
        description: 'S3 Key for the backup to restore e.g. 20250225083000'
        required: true
        type: string
      environment:
        description: 'Choose environment (test/production)'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - production

jobs:
  rollback:
    name: Revert S3 Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Restore Selected Backup
        run: |
          echo "Rolling back to ${{ inputs.backup_s3_key }}..."
          aws s3 sync s3://$AWS_S3_BUCKET_BACKUP/${{ inputs.backup_s3_key }}/ s3://$AWS_S3_BUCKET --delete
        env:
          AWS_S3_BUCKET: ${{ inputs.environment == 'test' && secrets.AWS_S3_BUCKET_DEV || secrets.AWS_S3_BUCKET_PROD }}
          AWS_S3_BUCKET_BACKUP: ${{ inputs.environment == 'test' && secrets.AWS_S3_BUCKET_BACKUP_DEV || secrets.AWS_S3_BUCKET_BACKUP_PROD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      
      - name: Invalidate CloudFront Cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ inputs.environment == 'test' && secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID_DEV || secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID_PROD }}
          PATHS: "/*"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
